title: Family Fantasy Football
description: Let's have some serious fun.
show_downloads: true
url: "http://sportsfamily.club"
google_analytics:
theme: jekyll-theme-cayman
defaults:
  -
  scope:
    path: "_slides"
  values:
    layout: "iframe"

collections:
  slides:
    output: true